### ISSUE TITLE
Missing enemy team

### ISSUE THREAD

**Issue by Forenzek** [evido/wotreplay-parser#13]
When I create any type of map it only shows data for my team and is missing all data from the enemy team.

**Comment by evido** [comment]
Do you have any example of such a replay. I just tried for myself, and still seems to work. I used the following replay as input: http://wotreplays.eu/site/5394107#teams and generated the following result.


![output](https://user-images.githubusercontent.com/1234187/82586943-a68fd600-9b98-11ea-8753-0a90de3775ad.png)

**Comment by Forenzek** [comment]
Yeah here are 2 of them [http://wotreplays.eu/site/5394141#cliff-forinzek-leopard_1](url) [http://wotreplays.eu/site/5394146#cliff-forinzek-leopard_1](url). 
This is what I got for the second one
![18_cliff_ctf](https://user-images.githubusercontent.com/20116465/82588618-171efe80-9b69-11ea-925d-cbc79e4e1cb6.png)

**Comment by pashok3d** [comment]
There is indeed some problem with parsing these replays. I assume, the probem is that "battle type" in these replays is "Global map", not "Regular".

**Comment by evido** [comment]
Last commits should solve the issue. The issue was that the JSON document where i was reading the information from, no longer contained the full team composition.
