### ISSUE TITLE
Cannot use parser

### ISSUE THREAD

**Issue by provincjalc** [evido/wotreplay-parser#14]
Hello,
i would like to use your parser for a small experiment of mine, but i am unable to start it. At have downloaded pre-build windows executor and then tried to start it.

I am using Windows 10 x64.

First error was that i got error for missing MSVCP120.DLL.

When dll was downloaded and added into windows folder i got another issue, that i don't know how to fix (error is attached). 

![error](https://user-images.githubusercontent.com/12050060/82525344-6b0df100-9b31-11ea-8de2-722496914ed5.png)

Can you help me?

Greetings

**Comment by evido** [comment]
How did you acquire that DLL the recommended method is to download the redistributable package from package. The provided zip seems to rely on both VS2012 and VS2013, which can be downloaded here:

- https://www.microsoft.com/en-us/download/details.aspx?id=30679
- https://www.microsoft.com/en-us/download/details.aspx?id=40784

Please note that you need the x86 version as the provided binaries are 32 bit.

**Comment by provincjalc** [comment]
Hello,

thank you. This is working now.
