### ISSUE TITLE
On PNG type output, both teams are using enemy_base.png element

### ISSUE THREAD

**Issue by tswinehart** [evido/wotreplay-parser#16]
When using the command "wotreplay-parser" --type png" the same element "enemy_base.png" is showing for both sides in CTF mode. Using the --type gif output is showing it correctly for the same replay file.

![demo - Copy](https://user-images.githubusercontent.com/33028154/84175001-55fbf200-aa4d-11ea-9137-98eb8cf6cff1.png)

![demo - Copy](https://user-images.githubusercontent.com/33028154/84175071-71ff9380-aa4d-11ea-9375-a406ba09b86d.gif)

Also can I recommend you please add a --version parameter for the program to assist in troubleshooting and issue submission? I would PR this myself, but have no skill in C++. Thank you for your excellent work on this project.

**Comment by evido** [comment]
Both issues resolved. Only thing I cannot solve  is the programming language used :).

**Comment by tswinehart** [comment]
Can confirm! Issue resolved, and new feature implemented on version 20200609.202453 ;)

Thank you for your timely resolution and bonus feature!!!
