### ISSUE TITLE
error while loading shared libraries: ?

### ISSUE THREAD

**Issue by JacobCZ** [evido/wotreplay-parser#6]
When trying to use this tool to convert the replay file to json, I get this error...

```error while loading shared libraries: ?: cannot open shared object file: No such file or directory```

**Comment by evido** [comment]
Could you provide some more details, did you try to build from sources yourself (if so provided some details about the platform) or did you use the provided windows binaries ?

**Comment by JacobCZ** [comment]
Oh sorry, I was in a hurry. I've used the provided binaries, I'm running Windows 10 Pro x64 (build 14390.0). This is the only error I got.

**Comment by evido** [comment]
I updated the zip file (https://drive.google.com/file/d/0B3nvac-cSAKRb1VGT2xkcEhnbnc/view?usp=sharing) , if you're still having issues you might need the following too: https://support.native-instruments.com/hc/en-us/articles/209571689-Windows-Error-Message-Missing-MSVCP120-dll-File
