### ISSUE TITLE
Parsing to json after patch 9.14

### ISSUE THREAD

**Issue by MarekFlis** [evido/wotreplay-parser#7]
It seems that program will crash when parsing .wotreplay from patches 9.14 and above when trying to parse into json. Is it true for you too or is it only problem on my machine? It works fine for previous patches up to 9.13. Maybe it has something to do with improved physics?

**Comment by evido** [comment]
Using the branch 'ubuntu' I'm able to execute parse the following replay without any issues: http://wotreplays.com/site/3266075#mines-vateszka-bat_-ch_tillon_155_55 . Could you try using that version of the code ?
